//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Outercurve Foundation")]
[assembly: AssemblyCopyright("Copyright © 2015 Outercurve Foundation.")]
[assembly: AssemblyVersion("2.1.0.923")]
[assembly: AssemblyFileVersion("2.1.0.923")]
[assembly: AssemblyInformationalVersion("2.1.0")]


